### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by BCCCz** [Radeity/LWE-based-fuzzy-extractor#1]
Apon.py文件中测试使用的那几个.pgm文件可以发我一份吗？最近刚好在学习模糊提取器方面的知识，想完整跑一次代码看看

**Comment by Radeity** [comment]
Apon.py只需要一个输入图片 -- 代码中是4.pgm，我用的是我自己的人脸采样图片不太方便直接给你了，你进行一下preprocess得到一张92*112的灰度图片即可。

**Comment by Radeity** [comment]
> 

Apon.py只需要一个输入图片 -- 代码中是4.pgm，我用的是我自己的人脸采样图片不太方便直接给你了，你进行一下preprocess得到一张92*112的灰度图片即可。

**Comment by BCCCz** [comment]
感谢你的回复，我又遇到了一个新问题，运行wen.py的时候出现了下面的错误，请问有什么解决方法吗
Traceback (most recent call last):
  File "/home/bc/Voice_AU/LWE-based-fuzzy-extractor/Wen18.py", line 135, in <module>
    r.resize(r.shape[0])
AttributeError: 'str' object has no attribute 'resize'

**Comment by Radeity** [comment]
是这样的，该main函数的为最开始测试第一个实现版本的代码，后来我将生物信息输入和模糊提取器做了结合，可能用法会不太一样，但你仍然可以仅通过比较Gen的输出和Rec输出是否相同来确定模糊提取器的正确性。
